### ISSUE TITLE
some confusion

### ISSUE THREAD

**Issue by boxyao** [wvinzh/WS_DAN_PyTorch#3]
pooling_features = raw_features*100 , Why multiply raw_features by 100?

**Comment by wvinzh** [comment]
Make the obtained gradient larger and speed up training，the value of raw_features is too small

**Comment by boxyao** [comment]
Is 100  a  experience value？

**Comment by boxyao** [comment]
I have ran the code. The test accuracy is very well, but the train and val  prec@1 and prec@5 are very samll values, such as 1.4, 1.5. Is it right？ Is  there something wrong with my trainning?

**Comment by wvinzh** [comment]
> Is 100 a experience value？

Maybe，I followed the settings in the official repo, [ws_dan](https://github.com/tau-yihouxiang/WS_DAN)

**Comment by wvinzh** [comment]
> I have ran the code. The test accuracy is very well, but the train and val prec@1 and prec@5 are very samll values, such as 1.4, 1.5. Is it right？ Is there something wrong with my trainning?

I think it is not normal, maybe you can check it carefully. 1.4 1.5 may be the loss values, not precisions

**Comment by wvinzh** [comment]
> > Is 100 a experience value？
> 
> Maybe，I followed the settings in the official repo, [ws_dan](https://github.com/tau-yihouxiang/WS_DAN)
